#!/usr/bin/env bash

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../ci-lib.sh"

# 0) Get pytorch wheel as argument
while getopts 't:' opt; do
	case "$opt" in
	t)
		TORCH_WHEEL="$(realpath "$OPTARG")"
		;;
	*)
		echo "Usage: $0 -t <pytorch_wheel>" 1>&2
		exit 1
		;;
	esac
done

if [ -z "$TORCH_WHEEL" ]; then
	echo "Usage: $0 -t <pytorch_wheel>" 1>&2
	exit 1
fi

# 1) Pull source and gen build environment
gen_build_dir_with_git 'https://github.com/intel/intel-extension-for-pytorch' -b xpu-main
setup_build_env

setup_uv_venv -r requirements.txt pip "$TORCH_WHEEL"

# 2) Set IPEX build configuration
CC="$(which gcc)"
export CC
CXX="$(which g++)"
export CXX
export INTELONEAPIROOT="$ONEAPI_ROOT"

# 3) Build & Archive
build_bdist_wheel
