#!/usr/bin/env bash

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../ci-lib.sh"

# 0) Get pytorch wheel as argument
while getopts 't:' opt; do
	case "$opt" in
	t)
		TORCH_WHEEL="$(realpath "$OPTARG")"
		;;
	*)
		echo "Usage: $0 -t <pytorch_wheel>" 1>&2
		exit 1
		;;
	esac
done

if [ -z "$TORCH_WHEEL" ]; then
	echo "Usage: $0 -t <pytorch_wheel>" 1>&2
	exit 1
fi

# 1) Pull source and gen build environment
gen_build_dir_with_git 'https://github.com/intel/torch-ccl'
setup_build_env

setup_uv_venv -r requirements.txt "$TORCH_WHEEL"

# FIXME need to checkout c27ded5 or create a patch because the repo version.txt is messed up
# git checkout c27ded5

# 2) Set torch-ccl build configuration
export ONECCL_BINDINGS_FOR_PYTORCH_BACKEND='xpu'
export INTELONEAPIROOT="$ONEAPI_ROOT"
export USE_SYSTEM_ONECCL='ON'
export COMPUTE_BACKEND='dpcpp'

# 3) Build & Archive
build_bdist_wheel
