#!/usr/bin/env bash

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../ci-lib.sh"

# 1) Pull source and gen build environment
gen_build_dir_with_git 'https://github.com/pytorch/pytorch' -b "$FRAMEWORKS_TORCH_VERSION"
setup_build_env

# Must use uv-managed python for development headers
setup_uv_venv --group dev pip mkl-static mkl-include

# TODO source compile the corresponding pinned triton-xpu version
# shellcheck source=/dev/null
source .venv/bin/activate
USE_XPU=1 make triton
deactivate

# 2) Set PyTorch build configuration
CC="$(which gcc)"
export CC
CXX="$(which g++)"
export CXX
export REL_WITH_DEB_INFO=1
export USE_CUDA=0
export USE_ROCM=0
export USE_MKLDNN=1
export USE_MKL=1
export USE_CUDNN=0
export USE_FBGEMM=1
export USE_NNPACK=1
export USE_QNNPACK=1
export USE_NCCL=0
export BUILD_CAFFE2_OPS=0
export BUILD_TEST=0
export USE_DISTRIBUTED=1
export USE_NUMA=0
export USE_MPI=1
export USE_XPU=1
export USE_XCCL=1
export INTEL_MKL_DIR="$MKLROOT"
export USE_AOT_DEVLIST='pvc'
export TORCH_XPU_ARCH_LIST='pvc'
export OCLOC_VERSION=24.39.1

# 3) Build & Archive
build_bdist_wheel
