#!/usr/bin/env bash

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../ci-lib.sh"

# 1) Pull source and gen build environment
gen_build_dir_with_git 'https://github.com/pytorch/pytorch' -b "$FRAMEWORKS_TORCH_VERSION"
setup_build_env

artifact_in "triton-*.whl"

# Must use uv-managed python for development headers
setup_uv_venv --group dev pip mkl-static mkl-include *.whl

# Use built pti-gpu
export C_INCLUDE_PATH="$FRAMEWORKS_RUN_DIR/pti-gpu/include:$C_INCLUDE_PATH"
export CPLUS_INCLUDE_PATH="$FRAMEWORKS_RUN_DIR/pti-gpu/include:$CPLUS_INCLUDE_PATH"
export LIBRARY_PATH="$FRAMEWORKS_RUN_DIR/pti-gpu/lib:$LIBRARY_PATH"
export Pti_DIR="$FRAMEWORKS_RUN_DIR/pti-gpu/lib/cmake/pti"

# Patch OpenMP flag failure
git am <<'EOF'
From b4bdb5ec6901174f3c059e881bd1a479097dd24c Mon Sep 17 00:00:00 2001
From: Ethan Wong <ewong@anl.gov>
Date: Mon, 27 Jul 2026 19:32:12 -0500
Subject: [PATCH] cmake/openmp: add flag check for IntelLLVM

Newer versions of oneAPI use "IntelLLVM" as the compiler ID. Currently,
cmake will fail to set the appropriate OpenMP flag, causing trivial
build errors on submodule dependencies.
---
 cmake/Modules/FindOpenMP.cmake | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/cmake/Modules/FindOpenMP.cmake b/cmake/Modules/FindOpenMP.cmake
index b027d63f1a7..cbe3e9fc1af 100644
--- a/cmake/Modules/FindOpenMP.cmake
+++ b/cmake/Modules/FindOpenMP.cmake
@@ -119,6 +119,12 @@ function(_OPENMP_FLAG_CANDIDATES LANG)
     else()
       set(OMP_FLAG_Intel "-qopenmp")
     endif()
+    if(CMAKE_${LANG}_COMPILER_ID STREQUAL "IntelLLVM" AND
+      "x${CMAKE_${LANG}_COMPILER_FRONTEND_VARIANT}" STREQUAL "xMSVC")
+      set(OMP_FLAG_IntelLLVM "-Qiopenmp")
+    else()
+      set(OMP_FLAG_IntelLLVM "-fiopenmp")
+    endif()
     set(OMP_FLAG_MIPSpro "-mp")
     if(__header_dir MATCHES ".*Microsoft Visual Studio.*")
       # MSVC header. No need to pass it as additional include.
-- 
2.50.1 (Apple Git-155)
EOF

# Patch SYCL version guard drop
git am <<'EOL'
From d875d65b53c6d879d3c979078f989b195c705f6a Mon Sep 17 00:00:00 2001
From: Ethan Wong <ewong@anl.gov>
Date: Fri, 31 Jul 2026 10:37:57 -0500
Subject: [PATCH] Revert "Drop sycl compiler guard less than 2026 for XPU
 (#191470)"

This reverts commit 15d589c8f6dc7278dee87552ac1ce0ee15d8232d.
---
 c10/xpu/XPUDeviceProp.h   |  2 ++
 c10/xpu/XPUFunctions.cpp  |  7 +++++++
 cmake/public/xpu.cmake    | 10 +++++++++-
 test/test_xpu.py          |  9 +++++----
 torch/csrc/xpu/Module.cpp |  7 ++++++-
 5 files changed, 29 insertions(+), 6 deletions(-)

diff --git a/c10/xpu/XPUDeviceProp.h b/c10/xpu/XPUDeviceProp.h
index 32e76ee3c89..7648fc8444a 100644
--- a/c10/xpu/XPUDeviceProp.h
+++ b/c10/xpu/XPUDeviceProp.h
@@ -223,8 +223,10 @@ struct C10_XPU_API DeviceProp{
     // ext properties.
     AT_FORALL_XPU_EXT_DEVICE_PROPERTIES(DEFINE_EXT_DEVICE_PROP)
 
+#if SYCL_COMPILER_VERSION >= 20260000
     // device aspects.
     DEFINE_DEVICE_ASPECT(is_integrated_gpu)
+#endif
 
     // device has aspects.
     AT_FORALL_XPU_DEVICE_ASPECT(DEFINE_DEVICE_HAS_ASPECT)
diff --git a/c10/xpu/XPUFunctions.cpp b/c10/xpu/XPUFunctions.cpp
index b52a576aacd..48610019041 100644
--- a/c10/xpu/XPUFunctions.cpp
+++ b/c10/xpu/XPUFunctions.cpp
@@ -43,7 +43,12 @@ void enumDevices(std::vector<std::unique_ptr<sycl::device>>& devices) {
   // See Note [Device Management] for more details.
   auto platform_list = sycl::platform::get_platforms();
   auto is_igpu = [](const sycl::device& device) {
+#if SYCL_COMPILER_VERSION < 20260000
+    // Generally, iGPUs share a unified memory subsystem with the host.
+    return device.get_info<sycl::info::device::host_unified_memory>();
+#else
     return device.has(sycl::aspect::ext_oneapi_is_integrated_gpu);
+#endif
   };
 
   // Check if a platform contains at least one GPU (either iGPU or dGPU).
@@ -184,7 +189,9 @@ void initDeviceProperties(DeviceProp* device_prop, DeviceIndex device) {
 
   AT_FORALL_XPU_EXT_DEVICE_PROPERTIES(ASSIGN_EXT_DEVICE_PROP);
 
+#if SYCL_COMPILER_VERSION >= 20260000
   ASSIGN_DEVICE_ASPECT(is_integrated_gpu)
+#endif
 
   AT_FORALL_XPU_DEVICE_ASPECT(ASSIGN_DEVICE_HAS_ASPECT);
 
diff --git a/cmake/public/xpu.cmake b/cmake/public/xpu.cmake
index dfa9183596f..25eb968fe93 100644
--- a/cmake/public/xpu.cmake
+++ b/cmake/public/xpu.cmake
@@ -72,7 +72,15 @@ string(APPEND XPU_HOST_CXX_FLAGS " -DUSE_XPU")
 string(APPEND XPU_HOST_CXX_FLAGS " -DSYCL_COMPILER_VERSION=${SYCL_COMPILER_VERSION}")
 
 if(DEFINED ENV{XPU_ENABLE_KINETO})
-  set(XPU_ENABLE_KINETO $ENV{XPU_ENABLE_KINETO})
+  set(XPU_ENABLE_KINETO TRUE)
+else()
+  set(XPU_ENABLE_KINETO FALSE)
+endif()
+
+if(WIN32)
+  if(${SYCL_COMPILER_VERSION} GREATER_EQUAL 20250101)
+    set(XPU_ENABLE_KINETO TRUE)
+  endif()
 else()
   set(XPU_ENABLE_KINETO TRUE)
 endif()
diff --git a/test/test_xpu.py b/test/test_xpu.py
index 75f24be2044..0ac59dcd3dd 100644
--- a/test/test_xpu.py
+++ b/test/test_xpu.py
@@ -179,10 +179,11 @@ class TestXpu(TestCase):
             len(str(device_properties.uuid)), 36
         )  # xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
         self.assertEqual(len(device_properties.uuid.bytes), 16)
-        self.assertEqual(
-            device_properties.is_integrated_gpu,
-            device_capability["is_integrated_gpu"],
-        )
+        if int(torch.version.xpu) >= 20260000:
+            self.assertEqual(
+                device_properties.is_integrated_gpu,
+                device_capability["is_integrated_gpu"],
+            )
 
     def test_get_device_capability(self):
         device_capability = torch.xpu.get_device_capability()
diff --git a/torch/csrc/xpu/Module.cpp b/torch/csrc/xpu/Module.cpp
index 34446e34a8c..c0309e49224 100644
--- a/torch/csrc/xpu/Module.cpp
+++ b/torch/csrc/xpu/Module.cpp
@@ -348,7 +348,9 @@ static void registerXpuDeviceProperties(PyObject* module) {
       ._(has_subgroup_2d_block_io)
 
   THXP_FORALL_DEVICE_PROPERTIES(DEFINE_READONLY_MEMBER)
+#if SYCL_COMPILER_VERSION >= 20260000
       .def_readonly("is_integrated_gpu", &DeviceProp::is_integrated_gpu)
+#endif
       .def_readonly("total_memory", &DeviceProp::global_mem_size)
       // TODO: Expose cache size by level when available from SYCL
       .def_readonly("last_level_cache_size", &DeviceProp::global_mem_cache_size)
@@ -385,7 +387,10 @@ static void registerXpuDeviceProperties(PyObject* module) {
                    << "], has_fp16=" << prop.has_fp16
                    << ", has_fp64=" << prop.has_fp64
                    << ", has_atomic64=" << prop.has_atomic64
-                   << ", is_integrated_gpu=" << prop.is_integrated_gpu << ")";
+#if SYCL_COMPILER_VERSION >= 20260000
+                   << ", is_integrated_gpu=" << prop.is_integrated_gpu
+#endif
+                   << ')';
             return std::move(stream).str();
           });
 }
-- 
2.50.1 (Apple Git-155)
EOL

# Patch torch-xpu-ops to support oneAPI
TORCH_XPU_OPS_COMMIT="$(cat third_party/xpu.txt)"
git clone 'https://github.com/intel/torch-xpu-ops.git' third_party/torch-xpu-ops
pushd third_party/torch-xpu-ops
git fetch origin "$TORCH_XPU_OPS_COMMIT"
git checkout FETCH_HEAD
git am <<'EOL'
From b5744c10b5f63657319d7d4bdb312754353c36db Mon Sep 17 00:00:00 2001
From: "Yu, Guangye" <guangye.yu@intel.com>
Date: Tue, 28 Jul 2026 17:21:30 +0800
Subject: [PATCH 1/2] Fix separate ops build failure due to Sleep.cpp (#4715)

# Motivation

Fix the broken build with `BUILD_SEPARATE_OPS=1` introduced by
https://github.com/intel/torch-xpu-ops/pull/4385
---
 src/BuildOnLinux.cmake | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)

diff --git a/src/BuildOnLinux.cmake b/src/BuildOnLinux.cmake
index 466f782f..72fb1fcb 100644
--- a/src/BuildOnLinux.cmake
+++ b/src/BuildOnLinux.cmake
@@ -40,7 +40,16 @@ if(BUILD_SEPARATE_OPS)
       ${sycl_lib}
       SHARED
       SYCL_SOURCES ${sycl_src})
-    target_link_libraries(torch_xpu_ops PUBLIC ${sycl_lib})
+
+    # Sleep.cpp provides at::xpu::sleep, used by libtorch_python but not by any
+    # operator in libtorch_xpu. Since no symbol is referenced within
+    # libtorch_xpu, --as-needed drops it, leaving at::xpu::sleep unresolved at
+    # load time. Force-keep it as a NEEDED dependency.
+    if(name STREQUAL "Sleep")
+      target_link_libraries(torch_xpu_ops PUBLIC "-Wl,--no-as-needed" ${sycl_lib} "-Wl,--as-needed")
+    else()
+      target_link_libraries(torch_xpu_ops PUBLIC ${sycl_lib})
+    endif()
     list(APPEND TORCH_XPU_OPS_LIBRARIES ${sycl_lib})
 
     # Decouple with PyTorch cmake definition.
-- 
2.50.1 (Apple Git-155)


From b6f5a976d18b23c14bfa6885a33319513cbfff4b Mon Sep 17 00:00:00 2001
From: Ethan Wong <ewong@anl.gov>
Date: Mon, 27 Jul 2026 22:29:27 -0500
Subject: [PATCH 2/2] cmake: support `IntelLLVM`

---
 CMakeLists.txt         | 8 ++++----
 cmake/BuildFlags.cmake | 6 +++---
 2 files changed, 7 insertions(+), 7 deletions(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index bdee938c..efb67683 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -66,10 +66,10 @@ if(USE_XCCL)
 endif()
 
 set(USE_SYCLTLA ON)
-if(WIN32 OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_VERSION VERSION_LESS 13.0)
-  set(USE_SYCLTLA OFF)
-  message(WARNING "SYCL-TLA is not build as it only supports GCC >= 13.0 as CXX Compiler on Linux Platform!")
-endif()
+# if(WIN32 OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_VERSION VERSION_LESS 13.0)
+#   set(USE_SYCLTLA OFF)
+#   message(WARNING "SYCL-TLA is not build as it only supports GCC >= 13.0 as CXX Compiler on Linux Platform!")
+# endif()
 
 if(USE_SYCLTLA)
   include(${TORCH_XPU_OPS_ROOT}/cmake/SYCLTLA.cmake)
diff --git a/cmake/BuildFlags.cmake b/cmake/BuildFlags.cmake
index 9629dc86..795648ae 100644
--- a/cmake/BuildFlags.cmake
+++ b/cmake/BuildFlags.cmake
@@ -31,7 +31,7 @@ function(CHECK_SYCL_FLAG FLAG VARIABLE_NAME)
 endfunction()
 
 macro(set_build_flags)
- set(_TORCH_XPU_OPS_SUPPORTED_COMPILERS "GNU" "MSVC")
+  set(_TORCH_XPU_OPS_SUPPORTED_COMPILERS "GNU" "MSVC" "IntelLLVM")
   if(NOT CMAKE_CXX_COMPILER_ID IN_LIST _TORCH_XPU_OPS_SUPPORTED_COMPILERS)
     message(WARNING "Not compiling with XPU. Currently only support GCC compiler on Linux and MSVC compiler on Windows as CXX compiler.")
     return()
@@ -71,7 +71,7 @@ macro(set_build_flags)
     elseif(CMAKE_BUILD_TYPE MATCHES RelWithDebInfo)
       list(APPEND SYCL_HOST_FLAGS /O2 /Z7)
     endif()
-  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
+  else()
     list(APPEND SYCL_HOST_FLAGS -fPIC)
     list(APPEND SYCL_HOST_FLAGS -std=${CPP_STD})
     list(APPEND SYCL_HOST_FLAGS -Wunused-variable)
@@ -140,7 +140,7 @@ macro(set_build_flags)
     list(APPEND SYCL_KERNEL_OPTIONS /Qftz-)
     # Suppress warnings about dllexport.
     list(APPEND SYCL_KERNEL_OPTIONS -Wno-ignored-attributes)
-  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
+  else()
     list(APPEND SYCL_KERNEL_OPTIONS -std=${CPP_STD})
     list(APPEND SYCL_KERNEL_OPTIONS -Wno-absolute-value)
     # -fma which we used before is an alias used for -ffp-contract=fast for compatibility reasons
-- 
2.50.1 (Apple Git-155)
EOL
popd
git am <<'EOL'
From 3d843079c8429068a41ec9647d6732ba2fe485f0 Mon Sep 17 00:00:00 2001
From: Ethan Wong <ewong@anl.gov>
Date: Mon, 27 Jul 2026 23:31:37 -0500
Subject: [PATCH] caffe2: don't checkout existing `torch-xpu-ops`

---
 caffe2/CMakeLists.txt | 28 ++++++++++++++--------------
 1 file changed, 14 insertions(+), 14 deletions(-)

diff --git a/caffe2/CMakeLists.txt b/caffe2/CMakeLists.txt
index abe7f74a656..b92a065b251 100644
--- a/caffe2/CMakeLists.txt
+++ b/caffe2/CMakeLists.txt
@@ -1199,20 +1199,20 @@ if(USE_XPU)
     if(NOT _exitcode EQUAL 0)
       message(FATAL_ERROR "Fail to clone ${TORCH_XPU_OPS_REPO_URL}")
     endif()
-  endif()
-  execute_process(
-    COMMAND git fetch --quiet
-    WORKING_DIRECTORY ${TORCH_XPU_OPS_DIR}
-    RESULT_VARIABLE _exitcode)
-  if(NOT _exitcode EQUAL 0)
-    message(FATAL_ERROR "Fail to fetch ${TORCH_XPU_OPS_REPO_URL}")
-  endif()
-  execute_process(
-    COMMAND git checkout --quiet ${TORCH_XPU_OPS_COMMIT}
-    WORKING_DIRECTORY ${TORCH_XPU_OPS_DIR}
-    RESULT_VARIABLE _exitcode)
-  if(NOT _exitcode EQUAL 0)
-    message(FATAL_ERROR "Fail to checkout ${TORCH_XPU_OPS_REPO_URL} to ${TORCH_XPU_OPS_COMMIT}")
+    execute_process(
+      COMMAND git fetch --quiet
+      WORKING_DIRECTORY ${TORCH_XPU_OPS_DIR}
+      RESULT_VARIABLE _exitcode)
+    if(NOT _exitcode EQUAL 0)
+      message(FATAL_ERROR "Fail to fetch ${TORCH_XPU_OPS_REPO_URL}")
+    endif()
+    execute_process(
+      COMMAND git checkout --quiet ${TORCH_XPU_OPS_COMMIT}
+      WORKING_DIRECTORY ${TORCH_XPU_OPS_DIR}
+      RESULT_VARIABLE _exitcode)
+    if(NOT _exitcode EQUAL 0)
+      message(FATAL_ERROR "Fail to checkout ${TORCH_XPU_OPS_REPO_URL} to ${TORCH_XPU_OPS_COMMIT}")
+    endif()
   endif()
 
   set(TORCH_XPU_OPS_INCLUDE_DIRS
-- 
2.50.1 (Apple Git-155)
EOL

# 2) Set PyTorch build configuration
export WERROR=0
export USE_CUDA=0
export USE_ROCM=0
export USE_MKLDNN=1
export USE_MKL=1
export USE_CUDNN=0
export USE_FBGEMM=1
export USE_NNPACK=1
export USE_QNNPACK=1
export USE_NCCL=0
export BUILD_CAFFE2_OPS=0
export BUILD_TEST=0
export USE_DISTRIBUTED=1
export USE_NUMA=0
export USE_MPI=1
export USE_XPU=1
export USE_XCCL=1
export USE_AOT_DEVLIST='pvc'
export TORCH_XPU_ARCH_LIST='pvc'

# 3) Build & Archive
build_bdist_wheel
artifact_out "torch-*.whl"
