# Common definitions for all jobs
spec:
  inputs:
    runner:
      options: [aurora, sunspot]
      default: aurora
      description: CI runners to use
    env:
      default: prod.env
      description: Set of environment variables to configure Frameworks
---

include:
  - project: 'anl/ci-resources/defaults'
    ref: main
    file:
      - '/runners.yml'

.common-runner:
  extends: .$[[ inputs.runner ]]-shell-runner
  timeout: 3h
  interruptible: true
  variables:
    ANL_AURORA_SCHEDULER_PARAMETERS: '-A datascience -l select=1,walltime=06:00:00,filesystems=home:flare -q prod'
    HTTP_PROXY:  'http://proxy.alcf.anl.gov:3128'
    HTTPS_PROXY: 'http://proxy.alcf.anl.gov:3128'
    http_proxy:  'http://proxy.alcf.anl.gov:3128'
    https_proxy: 'http://proxy.alcf.anl.gov:3128'
  before_script:
    - . $[[ inputs.env ]]

stages:
  - build
